project_id = "ufoketygwxdlusngppef"

[functions.identify-pest]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.identify-animal-disease]
verify_jwt = false

[functions.estimate-produce]
verify_jwt = false

[functions.check-planting-reminders]
verify_jwt = false

[functions.send-weather-notifications]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
