import { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';

type Translations = Record<string, Record<string, string>>;

const translations: Translations = {
  en: {
    // Navigation
    home: 'Home', scan: 'Scan', spray: 'Spray', ledger: 'Ledger', profile: 'Profile',
    weather: 'Weather', back: 'Back', school: 'School',

    // Auth
    signIn: 'Sign In', signUp: 'Create Account', email: 'Email', password: 'Password',
    country: 'Country', phoneRequired: 'Phone number is required', countryRequired: 'Country is required',
    signInWith: 'Sign in with your account', registerFor: 'Register for Imvelo',
    resetPassword: 'Reset Password', setNewPassword: 'Set New Password',
    enterEmailReset: 'Enter your email to receive a reset link', enterNewPassword: 'Enter your new password',
    fullName: 'Full Name', phone: 'Phone Number', phoneHint: 'For SMS weather alerts and farming tips',
    role: 'Role', farmer: 'Farmer', trader: 'Trader', extensionOfficer: 'Extension Officer',
    newPassword: 'New Password', confirmPassword: 'Confirm Password',
    pleaseWait: 'Please wait...', continueWithGoogle: 'Continue with Google',
    forgotPassword: 'Forgot Password?', dontHaveAccount: "Don't have an account? Sign Up",
    alreadyHaveAccount: 'Already have an account? Sign In', backToLogin: 'Back to Login',
    or: 'or', aboutUs: 'About Us', contact: 'Contact', privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',

    // Profile
    myProfile: 'My Profile', myInfo: 'My Information', location: 'Location',
    language: 'Preferred Language', save: 'Save Changes', logout: 'Logout',
    premiumMember: 'Premium Member', freePlan: 'Free Plan', managePlan: 'Manage Plan',
    upgradePlan: 'Upgrade Plan', uploading: 'Uploading...', expires: 'Expires',
    langHint: 'The AI assistant will respond in your preferred language',

    // Index / Home
    farmersBestFriend: "Farmer's Best Friend", upgrade: 'Upgrade Plan',
    cropMonitor: 'Crop Monitor', climateRisk: 'Climate Risk',
    aiHealthScan: 'AI health scan', volatilityEngine: 'Volatility engine',
    healthScan: 'Health Scan', pestSoilDisease: 'Pest, soil, disease',
    irrigation: 'Irrigation', rainWaterAdvisor: 'Rain & water advisor',
    livestock: 'Livestock', trackManage: 'Track & manage',
    cropRotation: 'Crop Rotation', planRotations: 'Plan rotations',
    fertilizer: 'Fertilizer', npkCalculator: 'NPK calculator',
    harvests: 'Harvests', trackYields: 'Track yields',
    priceAlerts: 'Price Alerts', marketTargets: 'Market targets',
    inventory: 'Inventory', trackSupplies: 'Track supplies',
    carbonScore: 'Carbon Score', sustainability: 'Sustainability',
    postHarvest: 'Post-Harvest', reduceLosses: 'Reduce losses',
    africanMarkets: 'African Markets', demandContacts: 'Demand & contacts',
    knowledgeGraph: 'Knowledge Graph', exploreData: 'Explore data',

    // Scanner
    identifyPestsDiseases: 'Identify Pests & Diseases',
    pests: 'Pests', animal: 'Animal', soil: 'Soil', yield: 'Yield',
    detectionHistory: 'Detection History', reportDeleted: 'Report deleted',
    failedDeleteReport: 'Failed to delete report',

    // Weather
    weatherForecast: 'Weather Forecast', today: 'Today', tomorrow: 'Tomorrow',
    highLow: 'High/Low', humidity: 'Humidity', wind: 'Wind',
    feelsLike: 'Feels like', sevenDayForecast: '7-Day Forecast',
    upgradeForForecast: 'Upgrade to Pro or Enterprise to see the full 7-day forecast and farming tips.',
    upgradeToPro: 'Upgrade to Pro', unableLoadWeather: 'Unable to load weather data. Please try again later.',
    farmingTipsToday: 'Farming Tips for Today',
    tipHighTemp: 'High temperature - Water your crops early morning or late evening to reduce evaporation.',
    tipRain: 'High chance of rain - Avoid spraying pesticides, as they may wash away.',
    tipWind: 'Windy conditions - Secure lightweight structures and avoid burning activities.',
    tipHumidity: 'High humidity - Monitor crops for fungal diseases.',
    tipGoodConditions: 'Good conditions for planting and outdoor farming activities.',

    // Upgrade
    choosePlan: 'Choose Your Plan', unlockTools: 'Unlock powerful farming tools',
    currentPlan: 'Current Plan', upgradeTo: 'Upgrade to', viewPlans: 'View Plans & Upgrade',
    popular: 'POPULAR', contactUs: 'Contact Us', contactSales: 'Contact Sales',
    perMonth: '/month', includedInPlan: 'Included in your plan',
    cancelAnytime: 'Cancel anytime. Enterprise plans are custom — contact our team.',

    // Best Practices
    bestPractices: 'Best Practices',
    seasonalPlantingGuide: 'Seasonal Planting Guide',
    learnBestTime: 'Learn the best time to plant your crops',
    soilManagement: 'Soil Management',
    keepSoilHealthy: 'Keep your soil healthy for better harvests',
    waterConservation: 'Water Conservation',
    tipsWaterManagement: 'Tips for efficient water management',

    // Extension Services
    extensionServices: 'Extension Services',
    callExtensionOfficers: 'Call Extension Officers',

    // Ledger
    digitalLedger: 'Digital Ledger', addEntry: 'Add Entry', income: 'Income', expense: 'Expense',
    all: 'All', budgets: 'Budgets', aiInsights: 'AI Insights',
    totalIncome: 'Total Income', totalExpenses: 'Total Expenses', netBalance: 'Net Balance',
    date: 'Date', category: 'Category', description: 'Description', amount: 'Amount',
    paymentMethod: 'Payment Method', referenceNumber: 'Reference Number', notes: 'Notes',
    addIncome: 'Add Income', addExpense: 'Add Expense', setBudget: 'Set Budget',
    monthlyLimit: 'Monthly Limit', alertThreshold: 'Alert Threshold',
    noEntries: 'No entries yet', exportPdf: 'Export PDF', currency: 'Currency',
    saveBudget: 'Save Budget', exceeded: 'Exceeded', warning: 'Warning', onTrack: 'On track',
    spent: 'spent', of: 'of', getAiInsights: 'Get AI Insights',
    analyzingFinances: 'Analyzing your finances...',
    financialAdvisor: 'Financial Advisor',
    advisorDesc: 'AI-powered financial advisor for your farm',
    askAdvisor: 'Ask Advisor',
    advisorPlaceholder: 'Ask about tax planning, investment, cash flow, risk management...',
    advisorThinking: 'Your financial advisor is thinking...',
    advisorWelcome: 'Your personal farm financial advisor. Ask about cash flow optimization, tax strategies, investment planning, risk management, loan readiness, or any financial question.',

    // Pesticide Calendar
    sprayCalendar: 'Spray Calendar',
    addSchedule: 'Add Schedule', cropName: 'Crop Name', pesticideName: 'Pesticide Name',
    applicationDate: 'Application Date', repeatInterval: 'Repeat Interval (days)',
    scheduled: 'Scheduled', completed: 'Completed', skipped: 'Skipped',
    markDone: 'Mark Done', skip: 'Skip',

    // Smart Irrigation
    smartIrrigation: 'Smart Irrigation',
    cropSelection: 'Crop Selection', soilType: 'Soil Type',
    getAnalysis: 'Get Analysis', refreshAnalysis: 'Refresh Analysis',
    waterNeeds: 'Water Needs', schedule: 'Schedule', tips: 'Tips',

    // Crop Monitoring
    cropMonitoring: 'Crop Monitoring',
    uploadCropImage: 'Upload a crop image for AI health analysis',
    cropType: 'Crop Type', plantingDate: 'Planting Date', growthStage: 'Growth Stage',
    selectCrop: 'Select crop', selectStage: 'Select stage',
    analyzingCrop: 'Analyzing crop health...',

    // Climate Risk
    climateRiskAnalysis: 'Climate Risk Analysis',
    riskOverview: 'Risk Overview', adaptations: 'Adaptations', forecast: 'Forecast',
    research: 'Research', liveConditions: 'Live Conditions', dataQuality: 'Data Quality',

    // Knowledge Graph
    knowledgeGraphExplorer: 'Knowledge Graph Explorer',
    searchNodes: 'Search nodes...', filterByType: 'Filter by type',
    allTypes: 'All Types', crops: 'Crops', treatments: 'Treatments',
    diseases: 'Diseases', soilTypes: 'Soil Types', seasons: 'Seasons', regions: 'Regions',
    relationships: 'Relationships', relatedNodes: 'Related Nodes',
    noRelationships: 'No relationships found',
    confidence: 'Confidence', strength: 'Strength',

    // African Markets
    africanMarketsTitle: 'African Markets',
    highDemandProducts: 'High-demand products & market contacts',
    pricesIn: 'Prices in',
    products: 'Products', markets: 'Markets',
    allDemand: 'All Demand', veryHigh: 'Very High', high: 'High', moderate: 'Moderate',
    refresh: 'Refresh', season: 'Season',
    marketContactsInfo: 'Major agricultural markets across Africa. Contact them for bulk pricing and trade opportunities.',

    // Farm Activities
    farmActivities: 'Farm Activities', addActivity: 'Add Activity',
    activityType: 'Activity Type', activityDate: 'Activity Date',

    // General
    loading: 'Loading...', error: 'Error', success: 'Success', cancel: 'Cancel',
    confirm: 'Confirm', delete: 'Delete', edit: 'Edit', close: 'Close',
    noData: 'No data available', tryAgain: 'Try again',
  },
  fr: {
    home: 'Accueil', scan: 'Scanner', spray: 'Pulvériser', ledger: 'Registre', profile: 'Profil',
    weather: 'Météo', back: 'Retour', school: 'École',
    signIn: 'Se connecter', signUp: 'Créer un compte', email: 'E-mail', password: 'Mot de passe',
    country: 'Pays', phoneRequired: 'Le numéro de téléphone est requis', countryRequired: 'Le pays est requis',
    signInWith: 'Connectez-vous à votre compte', registerFor: "S'inscrire à Imvelo",
    resetPassword: 'Réinitialiser le mot de passe', setNewPassword: 'Définir un nouveau mot de passe',
    enterEmailReset: 'Entrez votre email pour recevoir un lien de réinitialisation',
    enterNewPassword: 'Entrez votre nouveau mot de passe',
    fullName: 'Nom complet', phone: 'Numéro de téléphone',
    phoneHint: 'Pour les alertes météo par SMS et conseils agricoles',
    role: 'Rôle', farmer: 'Agriculteur', trader: 'Commerçant', extensionOfficer: 'Agent de vulgarisation',
    newPassword: 'Nouveau mot de passe', confirmPassword: 'Confirmer le mot de passe',
    pleaseWait: 'Veuillez patienter...', continueWithGoogle: 'Continuer avec Google',
    forgotPassword: 'Mot de passe oublié ?', dontHaveAccount: "Pas de compte ? S'inscrire",
    alreadyHaveAccount: 'Déjà un compte ? Se connecter', backToLogin: 'Retour à la connexion',
    or: 'ou', aboutUs: 'À propos', contact: 'Contact', privacyPolicy: 'Politique de confidentialité',
    termsOfService: "Conditions d'utilisation",
    myProfile: 'Mon Profil', myInfo: 'Mes Informations', location: 'Emplacement',
    language: 'Langue préférée', save: 'Enregistrer', logout: 'Déconnexion',
    premiumMember: 'Membre Premium', freePlan: 'Plan gratuit', managePlan: 'Gérer le plan',
    upgradePlan: 'Passer au plan supérieur', uploading: 'Téléchargement...', expires: 'Expire le',
    langHint: "L'assistant IA répondra dans votre langue préférée",
    farmersBestFriend: "Meilleur ami du fermier", upgrade: 'Passer au plan supérieur',
    cropMonitor: 'Suivi cultures', climateRisk: 'Risque climatique',
    aiHealthScan: 'Scan IA santé', volatilityEngine: 'Moteur de volatilité',
    healthScan: 'Scan santé', pestSoilDisease: 'Ravageurs, sol, maladie',
    irrigation: 'Irrigation', rainWaterAdvisor: "Conseiller pluie et eau",
    livestock: 'Bétail', trackManage: 'Suivre et gérer',
    cropRotation: 'Rotation des cultures', planRotations: 'Planifier les rotations',
    fertilizer: 'Engrais', npkCalculator: 'Calculateur NPK',
    harvests: 'Récoltes', trackYields: 'Suivre les rendements',
    priceAlerts: 'Alertes prix', marketTargets: 'Objectifs marché',
    inventory: 'Inventaire', trackSupplies: 'Suivre les stocks',
    carbonScore: 'Score carbone', sustainability: 'Durabilité',
    postHarvest: 'Post-récolte', reduceLosses: 'Réduire les pertes',
    africanMarkets: 'Marchés africains', demandContacts: 'Demande et contacts',
    knowledgeGraph: 'Graphe de connaissances', exploreData: 'Explorer les données',
    identifyPestsDiseases: 'Identifier ravageurs et maladies',
    pests: 'Ravageurs', animal: 'Animal', soil: 'Sol', yield: 'Rendement',
    detectionHistory: 'Historique de détection', reportDeleted: 'Rapport supprimé',
    failedDeleteReport: 'Échec de la suppression',
    weatherForecast: 'Prévisions météo', today: "Aujourd'hui", tomorrow: 'Demain',
    highLow: 'Max/Min', humidity: 'Humidité', wind: 'Vent',
    feelsLike: 'Ressenti', sevenDayForecast: 'Prévisions 7 jours',
    upgradeForForecast: 'Passez au plan Pro ou Enterprise pour voir les prévisions 7 jours.',
    upgradeToPro: 'Passer au Pro', unableLoadWeather: 'Impossible de charger les données météo.',
    farmingTipsToday: "Conseils agricoles du jour",
    tipHighTemp: "Température élevée - Arrosez tôt le matin ou tard le soir.",
    tipRain: "Forte chance de pluie - Évitez de pulvériser des pesticides.",
    tipWind: "Conditions venteuses - Sécurisez les structures légères.",
    tipHumidity: "Humidité élevée - Surveillez les maladies fongiques.",
    tipGoodConditions: "Bonnes conditions pour le semis et les activités agricoles.",
    choosePlan: 'Choisissez votre plan', unlockTools: 'Débloquez des outils agricoles puissants',
    currentPlan: 'Plan actuel', upgradeTo: 'Passer à', viewPlans: 'Voir les plans',
    popular: 'POPULAIRE', contactUs: 'Contactez-nous', contactSales: 'Contacter les ventes',
    perMonth: '/mois', includedInPlan: 'Inclus dans votre plan',
    cancelAnytime: 'Annulez à tout moment. Les plans Enterprise sont personnalisés.',
    bestPractices: 'Bonnes pratiques',
    seasonalPlantingGuide: 'Guide de plantation saisonnier',
    learnBestTime: 'Apprenez le meilleur moment pour planter',
    soilManagement: 'Gestion du sol',
    keepSoilHealthy: 'Gardez votre sol sain pour de meilleures récoltes',
    waterConservation: "Conservation de l'eau",
    tipsWaterManagement: "Conseils pour une gestion efficace de l'eau",
    extensionServices: "Services de vulgarisation", callExtensionOfficers: "Appeler les agents de vulgarisation",
    digitalLedger: 'Registre numérique', addEntry: 'Ajouter', income: 'Revenu', expense: 'Dépense',
    all: 'Tout', budgets: 'Budgets', aiInsights: 'Analyses IA',
    totalIncome: 'Revenu total', totalExpenses: 'Dépenses totales', netBalance: 'Solde net',
    date: 'Date', category: 'Catégorie', description: 'Description', amount: 'Montant',
    paymentMethod: 'Mode de paiement', referenceNumber: 'Numéro de référence', notes: 'Notes',
    addIncome: 'Ajouter un revenu', addExpense: 'Ajouter une dépense', setBudget: 'Définir le budget',
    monthlyLimit: 'Limite mensuelle', alertThreshold: "Seuil d'alerte",
    noEntries: 'Aucune entrée', exportPdf: 'Exporter PDF', currency: 'Devise',
    saveBudget: 'Enregistrer le budget', exceeded: 'Dépassé', warning: 'Attention', onTrack: 'En bonne voie',
    spent: 'dépensé', of: 'de', getAiInsights: 'Obtenir des analyses IA',
    analyzingFinances: 'Analyse de vos finances...',
    financialAdvisor: 'Conseiller financier',
    advisorDesc: 'Conseiller financier IA pour votre ferme',
    askAdvisor: 'Demander au conseiller',
    advisorPlaceholder: 'Posez des questions sur la fiscalité, l\'investissement, la trésorerie...',
    advisorThinking: 'Votre conseiller financier réfléchit...',
    advisorWelcome: 'Votre conseiller financier personnel. Posez des questions sur l\'optimisation de trésorerie, les stratégies fiscales, la planification d\'investissement ou la gestion des risques.',
    sprayCalendar: 'Calendrier de pulvérisation',
    addSchedule: 'Ajouter un programme', cropName: 'Nom de la culture', pesticideName: 'Nom du pesticide',
    applicationDate: "Date d'application", repeatInterval: 'Intervalle de répétition (jours)',
    scheduled: 'Programmé', completed: 'Terminé', skipped: 'Ignoré',
    markDone: 'Marquer terminé', skip: 'Ignorer',
    smartIrrigation: 'Irrigation intelligente',
    cropSelection: 'Sélection de culture', soilType: 'Type de sol',
    getAnalysis: 'Obtenir une analyse', refreshAnalysis: "Actualiser l'analyse",
    waterNeeds: "Besoins en eau", schedule: 'Programme', tips: 'Conseils',
    cropMonitoring: 'Suivi des cultures',
    uploadCropImage: "Téléchargez une image de culture pour l'analyse IA",
    cropType: 'Type de culture', plantingDate: 'Date de plantation', growthStage: 'Stade de croissance',
    selectCrop: 'Sélectionner une culture', selectStage: 'Sélectionner un stade',
    analyzingCrop: 'Analyse de la santé de la culture...',
    climateRiskAnalysis: 'Analyse du risque climatique',
    riskOverview: 'Aperçu des risques', adaptations: 'Adaptations', forecast: 'Prévisions',
    research: 'Recherche', liveConditions: 'Conditions en direct', dataQuality: 'Qualité des données',
    knowledgeGraphExplorer: 'Explorateur du graphe de connaissances',
    searchNodes: 'Rechercher des nœuds...', filterByType: 'Filtrer par type',
    allTypes: 'Tous les types', crops: 'Cultures', treatments: 'Traitements',
    diseases: 'Maladies', soilTypes: 'Types de sol', seasons: 'Saisons', regions: 'Régions',
    relationships: 'Relations', relatedNodes: 'Nœuds associés',
    noRelationships: 'Aucune relation trouvée',
    confidence: 'Confiance', strength: 'Force',
    africanMarketsTitle: 'Marchés africains',
    highDemandProducts: 'Produits à forte demande et contacts du marché',
    pricesIn: 'Prix en',
    products: 'Produits', markets: 'Marchés',
    allDemand: 'Toute demande', veryHigh: 'Très élevée', high: 'Élevée', moderate: 'Modérée',
    refresh: 'Actualiser', season: 'Saison',
    marketContactsInfo: 'Principaux marchés agricoles en Afrique. Contactez-les pour les prix en gros.',
    farmActivities: 'Activités agricoles', addActivity: 'Ajouter une activité',
    activityType: "Type d'activité", activityDate: "Date de l'activité",
    loading: 'Chargement...', error: 'Erreur', success: 'Succès', cancel: 'Annuler',
    confirm: 'Confirmer', delete: 'Supprimer', edit: 'Modifier', close: 'Fermer',
    noData: 'Aucune donnée disponible', tryAgain: 'Réessayer',
  },
  es: {
    home: 'Inicio', scan: 'Escanear', spray: 'Pulverizar', ledger: 'Libro', profile: 'Perfil',
    weather: 'Clima', back: 'Volver', school: 'Escuela',
    signIn: 'Iniciar sesión', signUp: 'Crear cuenta', email: 'Correo', password: 'Contraseña',
    country: 'País', phoneRequired: 'Se requiere teléfono', countryRequired: 'Se requiere país',
    signInWith: 'Inicia sesión con tu cuenta', registerFor: 'Regístrate en Imvelo',
    resetPassword: 'Restablecer contraseña', setNewPassword: 'Establecer nueva contraseña',
    enterEmailReset: 'Ingresa tu correo para recibir un enlace de restablecimiento',
    enterNewPassword: 'Ingresa tu nueva contraseña',
    fullName: 'Nombre completo', phone: 'Teléfono',
    phoneHint: 'Para alertas meteorológicas por SMS y consejos agrícolas',
    role: 'Rol', farmer: 'Agricultor', trader: 'Comerciante', extensionOfficer: 'Oficial de extensión',
    newPassword: 'Nueva contraseña', confirmPassword: 'Confirmar contraseña',
    pleaseWait: 'Por favor espere...', continueWithGoogle: 'Continuar con Google',
    forgotPassword: '¿Olvidaste tu contraseña?', dontHaveAccount: '¿No tienes cuenta? Regístrate',
    alreadyHaveAccount: '¿Ya tienes cuenta? Inicia sesión', backToLogin: 'Volver al inicio de sesión',
    or: 'o', aboutUs: 'Sobre nosotros', contact: 'Contacto', privacyPolicy: 'Política de privacidad',
    termsOfService: 'Términos de servicio',
    myProfile: 'Mi Perfil', myInfo: 'Mi Información', location: 'Ubicación',
    language: 'Idioma preferido', save: 'Guardar cambios', logout: 'Cerrar sesión',
    premiumMember: 'Miembro Premium', freePlan: 'Plan gratuito', managePlan: 'Gestionar plan',
    upgradePlan: 'Mejorar plan', uploading: 'Subiendo...', expires: 'Expira',
    langHint: 'El asistente IA responderá en tu idioma preferido',
    farmersBestFriend: 'Mejor amigo del agricultor', upgrade: 'Mejorar plan',
    cropMonitor: 'Monitor cultivos', climateRisk: 'Riesgo climático',
    aiHealthScan: 'Escaneo IA', volatilityEngine: 'Motor de volatilidad',
    healthScan: 'Escaneo de salud', pestSoilDisease: 'Plagas, suelo, enfermedad',
    irrigation: 'Riego', rainWaterAdvisor: 'Asesor de lluvia y agua',
    livestock: 'Ganado', trackManage: 'Seguir y gestionar',
    cropRotation: 'Rotación de cultivos', planRotations: 'Planificar rotaciones',
    fertilizer: 'Fertilizante', npkCalculator: 'Calculadora NPK',
    harvests: 'Cosechas', trackYields: 'Seguir rendimientos',
    priceAlerts: 'Alertas de precios', marketTargets: 'Objetivos de mercado',
    inventory: 'Inventario', trackSupplies: 'Seguir suministros',
    carbonScore: 'Huella de carbono', sustainability: 'Sostenibilidad',
    postHarvest: 'Post-cosecha', reduceLosses: 'Reducir pérdidas',
    africanMarkets: 'Mercados africanos', demandContacts: 'Demanda y contactos',
    knowledgeGraph: 'Grafo de conocimiento', exploreData: 'Explorar datos',
    identifyPestsDiseases: 'Identificar plagas y enfermedades',
    pests: 'Plagas', animal: 'Animal', soil: 'Suelo', yield: 'Rendimiento',
    detectionHistory: 'Historial de detección', reportDeleted: 'Reporte eliminado',
    failedDeleteReport: 'Error al eliminar reporte',
    weatherForecast: 'Pronóstico del clima', today: 'Hoy', tomorrow: 'Mañana',
    highLow: 'Máx/Mín', humidity: 'Humedad', wind: 'Viento',
    feelsLike: 'Sensación', sevenDayForecast: 'Pronóstico 7 días',
    upgradeForForecast: 'Mejora a Pro o Enterprise para ver el pronóstico de 7 días.',
    upgradeToPro: 'Mejorar a Pro', unableLoadWeather: 'No se pudieron cargar los datos del clima.',
    farmingTipsToday: 'Consejos agrícolas de hoy',
    tipHighTemp: 'Temperatura alta - Riegue temprano en la mañana o tarde en la noche.',
    tipRain: 'Alta probabilidad de lluvia - Evite pulverizar pesticidas.',
    tipWind: 'Condiciones ventosas - Asegure las estructuras ligeras.',
    tipHumidity: 'Alta humedad - Vigile las enfermedades fúngicas.',
    tipGoodConditions: 'Buenas condiciones para siembra y actividades agrícolas.',
    choosePlan: 'Elige tu plan', unlockTools: 'Desbloquea herramientas agrícolas',
    currentPlan: 'Plan actual', upgradeTo: 'Mejorar a', viewPlans: 'Ver planes',
    popular: 'POPULAR', contactUs: 'Contáctenos', contactSales: 'Contactar ventas',
    perMonth: '/mes', includedInPlan: 'Incluido en tu plan',
    cancelAnytime: 'Cancela en cualquier momento. Los planes Enterprise son personalizados.',
    bestPractices: 'Buenas prácticas',
    seasonalPlantingGuide: 'Guía de siembra estacional',
    learnBestTime: 'Aprende el mejor momento para sembrar',
    soilManagement: 'Gestión del suelo',
    keepSoilHealthy: 'Mantén tu suelo sano para mejores cosechas',
    waterConservation: 'Conservación del agua',
    tipsWaterManagement: 'Consejos para una gestión eficiente del agua',
    extensionServices: 'Servicios de extensión', callExtensionOfficers: 'Llamar a oficiales de extensión',
    digitalLedger: 'Libro digital', addEntry: 'Agregar', income: 'Ingreso', expense: 'Gasto',
    all: 'Todo', budgets: 'Presupuestos', aiInsights: 'Análisis IA',
    totalIncome: 'Ingreso total', totalExpenses: 'Gastos totales', netBalance: 'Balance neto',
    date: 'Fecha', category: 'Categoría', description: 'Descripción', amount: 'Monto',
    paymentMethod: 'Método de pago', referenceNumber: 'Número de referencia', notes: 'Notas',
    addIncome: 'Agregar ingreso', addExpense: 'Agregar gasto', setBudget: 'Establecer presupuesto',
    monthlyLimit: 'Límite mensual', alertThreshold: 'Umbral de alerta',
    noEntries: 'Sin entradas', exportPdf: 'Exportar PDF', currency: 'Moneda',
    saveBudget: 'Guardar presupuesto', exceeded: 'Excedido', warning: 'Advertencia', onTrack: 'En camino',
    spent: 'gastado', of: 'de', getAiInsights: 'Obtener análisis IA',
    analyzingFinances: 'Analizando tus finanzas...',
    financialAdvisor: 'Asesor financiero',
    advisorDesc: 'Asesor financiero IA para tu granja',
    askAdvisor: 'Preguntar al asesor',
    advisorPlaceholder: 'Pregunte sobre planificación fiscal, inversión, flujo de caja...',
    advisorThinking: 'Su asesor financiero está pensando...',
    advisorWelcome: 'Su asesor financiero personal. Pregunte sobre optimización de flujo de caja, estrategias fiscales, planificación de inversiones o gestión de riesgos.',
    sprayCalendar: 'Calendario de pulverización',
    addSchedule: 'Agregar programa', cropName: 'Nombre del cultivo', pesticideName: 'Nombre del pesticida',
    applicationDate: 'Fecha de aplicación', repeatInterval: 'Intervalo de repetición (días)',
    scheduled: 'Programado', completed: 'Completado', skipped: 'Omitido',
    markDone: 'Marcar hecho', skip: 'Omitir',
    smartIrrigation: 'Riego inteligente',
    cropSelection: 'Selección de cultivo', soilType: 'Tipo de suelo',
    getAnalysis: 'Obtener análisis', refreshAnalysis: 'Actualizar análisis',
    waterNeeds: 'Necesidades de agua', schedule: 'Programa', tips: 'Consejos',
    cropMonitoring: 'Monitoreo de cultivos',
    uploadCropImage: 'Sube una imagen del cultivo para análisis IA',
    cropType: 'Tipo de cultivo', plantingDate: 'Fecha de siembra', growthStage: 'Etapa de crecimiento',
    selectCrop: 'Seleccionar cultivo', selectStage: 'Seleccionar etapa',
    analyzingCrop: 'Analizando salud del cultivo...',
    climateRiskAnalysis: 'Análisis de riesgo climático',
    riskOverview: 'Resumen de riesgos', adaptations: 'Adaptaciones', forecast: 'Pronóstico',
    research: 'Investigación', liveConditions: 'Condiciones en vivo', dataQuality: 'Calidad de datos',
    knowledgeGraphExplorer: 'Explorador del grafo de conocimiento',
    searchNodes: 'Buscar nodos...', filterByType: 'Filtrar por tipo',
    allTypes: 'Todos los tipos', crops: 'Cultivos', treatments: 'Tratamientos',
    diseases: 'Enfermedades', soilTypes: 'Tipos de suelo', seasons: 'Estaciones', regions: 'Regiones',
    relationships: 'Relaciones', relatedNodes: 'Nodos relacionados',
    noRelationships: 'No se encontraron relaciones',
    confidence: 'Confianza', strength: 'Fuerza',
    africanMarketsTitle: 'Mercados africanos',
    highDemandProducts: 'Productos de alta demanda y contactos del mercado',
    pricesIn: 'Precios en',
    products: 'Productos', markets: 'Mercados',
    allDemand: 'Toda demanda', veryHigh: 'Muy alta', high: 'Alta', moderate: 'Moderada',
    refresh: 'Actualizar', season: 'Temporada',
    marketContactsInfo: 'Principales mercados agrícolas en África. Contáctelos para precios al por mayor.',
    farmActivities: 'Actividades agrícolas', addActivity: 'Agregar actividad',
    activityType: 'Tipo de actividad', activityDate: 'Fecha de actividad',
    loading: 'Cargando...', error: 'Error', success: 'Éxito', cancel: 'Cancelar',
    confirm: 'Confirmar', delete: 'Eliminar', edit: 'Editar', close: 'Cerrar',
    noData: 'Sin datos disponibles', tryAgain: 'Intentar de nuevo',
  },
  sw: {
    home: 'Nyumbani', scan: 'Changanua', spray: 'Nyunyizia', ledger: 'Daftari', profile: 'Wasifu',
    weather: 'Hali ya hewa', back: 'Rudi', school: 'Shule',
    signIn: 'Ingia', signUp: 'Jisajili', email: 'Barua pepe', password: 'Nywila',
    country: 'Nchi', phoneRequired: 'Nambari ya simu inahitajika', countryRequired: 'Nchi inahitajika',
    signInWith: 'Ingia na akaunti yako', registerFor: 'Jisajili kwa Imvelo',
    resetPassword: 'Weka upya nywila', setNewPassword: 'Weka nywila mpya',
    enterEmailReset: 'Ingiza barua pepe yako kupokea kiungo cha kuweka upya',
    enterNewPassword: 'Ingiza nywila yako mpya',
    fullName: 'Jina kamili', phone: 'Nambari ya simu',
    phoneHint: 'Kwa arifa za hali ya hewa na vidokezo vya kilimo',
    role: 'Jukumu', farmer: 'Mkulima', trader: 'Mfanyabiashara', extensionOfficer: 'Afisa wa ugani',
    newPassword: 'Nywila mpya', confirmPassword: 'Thibitisha nywila',
    pleaseWait: 'Tafadhali subiri...', continueWithGoogle: 'Endelea na Google',
    forgotPassword: 'Umesahau nywila?', dontHaveAccount: 'Huna akaunti? Jisajili',
    alreadyHaveAccount: 'Una akaunti tayari? Ingia', backToLogin: 'Rudi kuingia',
    or: 'au', aboutUs: 'Kuhusu sisi', contact: 'Wasiliana', privacyPolicy: 'Sera ya faragha',
    termsOfService: 'Masharti ya huduma',
    myProfile: 'Wasifu Wangu', myInfo: 'Taarifa Zangu', location: 'Mahali',
    language: 'Lugha unayopendelea', save: 'Hifadhi mabadiliko', logout: 'Toka',
    premiumMember: 'Mwanachama wa Premium', freePlan: 'Mpango wa bure', managePlan: 'Simamia mpango',
    upgradePlan: 'Panda mpango', uploading: 'Inapakia...', expires: 'Inaisha',
    langHint: 'Msaidizi wa AI atajibu kwa lugha yako unayopendelea',
    farmersBestFriend: 'Rafiki bora wa mkulima', upgrade: 'Panda mpango',
    cropMonitor: 'Ufuatiliaji mazao', climateRisk: 'Hatari ya hali ya hewa',
    aiHealthScan: 'Uchunguzi wa AI', volatilityEngine: 'Injini ya mabadiliko',
    healthScan: 'Uchunguzi wa afya', pestSoilDisease: 'Wadudu, udongo, ugonjwa',
    irrigation: 'Umwagiliaji', rainWaterAdvisor: 'Mshauri wa mvua na maji',
    livestock: 'Mifugo', trackManage: 'Fuatilia na simamia',
    cropRotation: 'Mzunguko wa mazao', planRotations: 'Panga mzunguko',
    fertilizer: 'Mbolea', npkCalculator: 'Kikokotoo cha NPK',
    harvests: 'Mavuno', trackYields: 'Fuatilia mavuno',
    priceAlerts: 'Arifa za bei', marketTargets: 'Malengo ya soko',
    inventory: 'Hesabu ya mali', trackSupplies: 'Fuatilia vifaa',
    carbonScore: 'Alama ya kaboni', sustainability: 'Uendelevu',
    postHarvest: 'Baada ya mavuno', reduceLosses: 'Punguza hasara',
    africanMarkets: 'Masoko ya Afrika', demandContacts: 'Mahitaji na mawasiliano',
    knowledgeGraph: 'Grafu ya maarifa', exploreData: 'Chunguza data',
    identifyPestsDiseases: 'Tambua wadudu na magonjwa',
    pests: 'Wadudu', animal: 'Mnyama', soil: 'Udongo', yield: 'Mavuno',
    detectionHistory: 'Historia ya ugunduzi', reportDeleted: 'Ripoti imefutwa',
    failedDeleteReport: 'Imeshindwa kufuta ripoti',
    weatherForecast: 'Utabiri wa hali ya hewa', today: 'Leo', tomorrow: 'Kesho',
    highLow: 'Juu/Chini', humidity: 'Unyevu', wind: 'Upepo',
    feelsLike: 'Inahisi kama', sevenDayForecast: 'Utabiri wa siku 7',
    upgradeForForecast: 'Panda hadi Pro au Enterprise kuona utabiri wa siku 7.',
    upgradeToPro: 'Panda hadi Pro', unableLoadWeather: 'Imeshindwa kupakia data ya hali ya hewa.',
    farmingTipsToday: 'Vidokezo vya kilimo kwa leo',
    tipHighTemp: 'Joto kali - Mwagilia asubuhi au jioni ili kupunguza uvukizi.',
    tipRain: 'Uwezekano mkubwa wa mvua - Epuka kunyunyizia dawa.',
    tipWind: 'Hali ya upepo - Imarisha miundo nyepesi.',
    tipHumidity: 'Unyevu mkubwa - Fuatilia magonjwa ya kuvu.',
    tipGoodConditions: 'Hali nzuri kwa kupanda na shughuli za shambani.',
    choosePlan: 'Chagua mpango wako', unlockTools: 'Fungua zana za kilimo',
    currentPlan: 'Mpango wa sasa', upgradeTo: 'Panda hadi', viewPlans: 'Tazama mipango',
    popular: 'MAARUFU', contactUs: 'Wasiliana nasi', contactSales: 'Wasiliana na mauzo',
    perMonth: '/mwezi', includedInPlan: 'Imejumuishwa katika mpango wako',
    cancelAnytime: 'Ghairi wakati wowote. Mipango ya Enterprise ni maalum.',
    bestPractices: 'Mbinu bora',
    seasonalPlantingGuide: 'Mwongozo wa kupanda wa msimu',
    learnBestTime: 'Jifunze wakati bora wa kupanda',
    soilManagement: 'Usimamizi wa udongo',
    keepSoilHealthy: 'Weka udongo wako wenye afya kwa mavuno bora',
    waterConservation: 'Uhifadhi wa maji',
    tipsWaterManagement: 'Vidokezo vya usimamizi bora wa maji',
    extensionServices: 'Huduma za ugani', callExtensionOfficers: 'Piga simu kwa maafisa wa ugani',
    digitalLedger: 'Daftari la dijitali', addEntry: 'Ongeza', income: 'Mapato', expense: 'Gharama',
    all: 'Zote', budgets: 'Bajeti', aiInsights: 'Uchambuzi wa AI',
    totalIncome: 'Jumla ya mapato', totalExpenses: 'Jumla ya gharama', netBalance: 'Salio halisi',
    date: 'Tarehe', category: 'Jamii', description: 'Maelezo', amount: 'Kiasi',
    paymentMethod: 'Njia ya malipo', referenceNumber: 'Nambari ya kumbukumbu', notes: 'Maelezo',
    addIncome: 'Ongeza mapato', addExpense: 'Ongeza gharama', setBudget: 'Weka bajeti',
    monthlyLimit: 'Kikomo cha mwezi', alertThreshold: 'Kizingiti cha tahadhari',
    noEntries: 'Hakuna maingizo', exportPdf: 'Hamisha PDF', currency: 'Sarafu',
    saveBudget: 'Hifadhi bajeti', exceeded: 'Imezidi', warning: 'Onyo', onTrack: 'Njia nzuri',
    spent: 'imetumika', of: 'ya', getAiInsights: 'Pata uchambuzi wa AI',
    analyzingFinances: 'Inachambua fedha zako...',
    financialAdvisor: 'Mshauri wa fedha',
    advisorDesc: 'Mshauri wa fedha wa AI kwa shamba lako',
    askAdvisor: 'Uliza mshauri',
    advisorPlaceholder: 'Uliza kuhusu kodi, uwekezaji, mtiririko wa fedha...',
    advisorThinking: 'Mshauri wako wa fedha anafikiria...',
    advisorWelcome: 'Mshauri wako binafsi wa fedha za shamba. Uliza kuhusu mtiririko wa fedha, mikakati ya kodi, mipango ya uwekezaji, au usimamizi wa hatari.',
    sprayCalendar: 'Kalenda ya kunyunyizia',
    addSchedule: 'Ongeza ratiba', cropName: 'Jina la zao', pesticideName: 'Jina la dawa',
    applicationDate: 'Tarehe ya matumizi', repeatInterval: 'Muda wa kurudia (siku)',
    scheduled: 'Imepangwa', completed: 'Imekamilika', skipped: 'Imerukwa',
    markDone: 'Weka imekamilika', skip: 'Ruka',
    smartIrrigation: 'Umwagiliaji mahiri',
    cropSelection: 'Uchaguzi wa zao', soilType: 'Aina ya udongo',
    getAnalysis: 'Pata uchambuzi', refreshAnalysis: 'Sasisha uchambuzi',
    waterNeeds: 'Mahitaji ya maji', schedule: 'Ratiba', tips: 'Vidokezo',
    cropMonitoring: 'Ufuatiliaji wa mazao',
    uploadCropImage: 'Pakia picha ya zao kwa uchambuzi wa AI',
    cropType: 'Aina ya zao', plantingDate: 'Tarehe ya kupanda', growthStage: 'Hatua ya ukuaji',
    selectCrop: 'Chagua zao', selectStage: 'Chagua hatua',
    analyzingCrop: 'Inachambua afya ya zao...',
    climateRiskAnalysis: 'Uchambuzi wa hatari ya hali ya hewa',
    riskOverview: 'Muhtasari wa hatari', adaptations: 'Marekebisho', forecast: 'Utabiri',
    research: 'Utafiti', liveConditions: 'Hali ya sasa', dataQuality: 'Ubora wa data',
    knowledgeGraphExplorer: 'Kichunguzi cha grafu ya maarifa',
    searchNodes: 'Tafuta nodi...', filterByType: 'Chuja kwa aina',
    allTypes: 'Aina zote', crops: 'Mazao', treatments: 'Matibabu',
    diseases: 'Magonjwa', soilTypes: 'Aina za udongo', seasons: 'Misimu', regions: 'Mikoa',
    relationships: 'Mahusiano', relatedNodes: 'Nodi zinazohusiana',
    noRelationships: 'Hakuna mahusiano yaliyopatikana',
    confidence: 'Imani', strength: 'Nguvu',
    africanMarketsTitle: 'Masoko ya Afrika',
    highDemandProducts: 'Bidhaa zenye mahitaji makubwa na mawasiliano ya soko',
    pricesIn: 'Bei katika',
    products: 'Bidhaa', markets: 'Masoko',
    allDemand: 'Mahitaji yote', veryHigh: 'Juu sana', high: 'Juu', moderate: 'Wastani',
    refresh: 'Sasisha', season: 'Msimu',
    marketContactsInfo: 'Masoko makubwa ya kilimo barani Afrika. Wasiliana nao kwa bei za jumla.',
    farmActivities: 'Shughuli za shamba', addActivity: 'Ongeza shughuli',
    activityType: 'Aina ya shughuli', activityDate: 'Tarehe ya shughuli',
    loading: 'Inapakia...', error: 'Hitilafu', success: 'Mafanikio', cancel: 'Ghairi',
    confirm: 'Thibitisha', delete: 'Futa', edit: 'Hariri', close: 'Funga',
    noData: 'Hakuna data', tryAgain: 'Jaribu tena',
  },
  ss: {
    home: 'Ekhaya', scan: 'Hlola', spray: 'Fafata', ledger: 'Incwadzi', profile: 'Umuntfu',
    weather: 'Simo selitulu', back: 'Buyela', school: 'Sikolo',
    signIn: 'Ngena', signUp: 'Bhalisa', email: 'I-imeyili', password: 'Liphasiwedi',
    country: 'Live', phoneRequired: 'Inombolo yelucingo iyadingeka', countryRequired: 'Live liyadingeka',
    signInWith: 'Ngena nge-akhawunti yakho', registerFor: 'Bhalisa ku-Imvelo',
    resetPassword: 'Setha kabusha liphasiwedi', setNewPassword: 'Beka liphasiwedi lelisha',
    enterEmailReset: 'Faka i-imeyili yakho kutfola isixhumanisi sekusetha kabusha',
    enterNewPassword: 'Faka liphasiwedi lakho lelisha',
    fullName: 'Ligama lephelele', phone: 'Inombolo yelucingo',
    phoneHint: 'Kwetatiselwa ngesimo selitulu ngemsedzi nemibiko yekulima',
    role: 'Indzima', farmer: 'Umlimi', trader: 'Umtsengisi', extensionOfficer: 'Balimisi',
    newPassword: 'Liphasiwedi lelisha', confirmPassword: 'Cinisekisa liphasiwedi',
    pleaseWait: 'Sicela ulindze...', continueWithGoogle: 'Chubeka nge-Google',
    forgotPassword: 'Ukhohlwe liphasiwedi?', dontHaveAccount: 'Awunayo i-akhawunti? Bhalisa',
    alreadyHaveAccount: 'Sewunayo i-akhawunti? Ngena', backToLogin: 'Buyela ekungenenI',
    or: 'noma', aboutUs: 'Ngatsi', contact: 'Tsintsana', privacyPolicy: 'Umtsetfo wekufihla',
    termsOfService: 'Imigomo yelusito',
    myProfile: 'Umuntfu Wami', myInfo: 'Lwati Lwami', location: 'Indzawo',
    language: 'Lulwimi lolukhetsako', save: 'Gcina kugucuka', logout: 'Phuma',
    premiumMember: 'Lilunga le-Premium', freePlan: 'Licebo lelimahhala', managePlan: 'Lawula licebo',
    upgradePlan: 'Khuphula licebo', uploading: 'Kufaka...', expires: 'Kuphela',
    langHint: 'Umsiti we-AI utawuphendvula ngelulwimi lwakho lolukhetsako',
    farmersBestFriend: 'Umngani lomkhulu wemlimi', upgrade: 'Khuphula licebo',
    cropMonitor: 'Kubuka tilimo', climateRisk: 'Ingoti yelitulu',
    aiHealthScan: 'Kuhlola kwe-AI', volatilityEngine: 'Injini yekugucula',
    healthScan: 'Kuhlola imphilo', pestSoilDisease: 'Tilwanyana, umhlaba, sifo',
    irrigation: 'Kunisela', rainWaterAdvisor: 'Umeluleki wemvula nemanti',
    livestock: 'Tifuyo', trackManage: 'Landzela uphatsise',
    cropRotation: 'Kujikisa tilimo', planRotations: 'Hlela kujikisa',
    fertilizer: 'Umcuba', npkCalculator: 'Sibali se-NPK',
    harvests: 'Tivuno', trackYields: 'Landzela tivuno',
    priceAlerts: 'Tecwayiso tetintengo', marketTargets: 'Imigomo yemakethe',
    inventory: 'Timphahla', trackSupplies: 'Landzela timphahla',
    carbonScore: 'Emaphuzu ekhaboni', sustainability: 'Kugcineka',
    postHarvest: 'Emva kwesivuno', reduceLosses: 'Nciphisa kulahlekelwa',
    africanMarkets: 'Timakethe tase-Afrika', demandContacts: 'Sidzingo nekutsintsana',
    knowledgeGraph: 'Igrafu yelwati', exploreData: 'Hlola idatha',
    identifyPestsDiseases: 'Bona tilwanyana netifo',
    pests: 'Tilwanyana', animal: 'Silwane', soil: 'Umhlaba', yield: 'Sivuno',
    detectionHistory: 'Umlando wekutfola', reportDeleted: 'Umbiko ususiwe',
    failedDeleteReport: 'Kwehluleka kususa umbiko',
    weatherForecast: 'Simo selitulu', today: 'Lamuhla', tomorrow: 'Kusasa',
    highLow: 'Phezulu/Phansi', humidity: 'Buswanti', wind: 'Umoya',
    feelsLike: 'Kutiva njenge', sevenDayForecast: 'Sibikezelo semalanga la-7',
    upgradeForForecast: 'Khuphulela ku-Pro noma Enterprise kubona sibikezelo semalanga la-7.',
    upgradeToPro: 'Khuphulela ku-Pro', unableLoadWeather: 'Ayikwatanga kulayisha data yesimo selitulu.',
    farmingTipsToday: 'Imibiko yekulima yalamuhla',
    tipHighTemp: 'Kushisa kakhulu - Nisela ekuseni noma kusihlwa.',
    tipRain: 'Litfuba lelikhulu lemvula - Ungafafati imitsi.',
    tipWind: 'Simo semoya - Cinisekisa takhiwo letikhanyako.',
    tipHumidity: 'Buswanti lobuphakeme - Bheka tifo tekubolela.',
    tipGoodConditions: 'Simo lesihle sekutjala nemisebenti yekuhlanyela.',
    choosePlan: 'Khetsa licebo lakho', unlockTools: 'Vula emathuluzi ekulima',
    currentPlan: 'Licebo lanyalo', upgradeTo: 'Khuphulela ku', viewPlans: 'Buka emacebo',
    popular: 'YATIWA', contactUs: 'Tsintsana natsi', contactSales: 'Tsintsana nekutsengisa',
    perMonth: '/ngenyanga', includedInPlan: 'Kufakwe kulicebo lakho',
    cancelAnytime: 'Khansela noma nini. Emacebo e-Enterprise amayelana.',
    bestPractices: 'Tindlela letinhle',
    seasonalPlantingGuide: 'Umhlahlandlela wekutjala wesikhatsi',
    learnBestTime: 'Fundza sikhatsi lesihle sekutjala',
    soilManagement: 'Kuphatfwa kwemhlaba',
    keepSoilHealthy: 'Gcina umhlaba wakho uphilile',
    waterConservation: 'Kulondvolota emanti',
    tipsWaterManagement: 'Imibiko yekuphatfwa kahle kwemanti',
    extensionServices: 'Balimisi', callExtensionOfficers: 'Shayela balimisi',
    digitalLedger: 'Incwadzi yedijithali', addEntry: 'Engeta', income: 'Imali lengenako', expense: 'Indleko',
    all: 'Konkhe', budgets: 'Emabhajethili', aiInsights: 'Lucwaningo lwe-AI',
    totalIncome: 'Imali yonkhe lengenako', totalExpenses: 'Tindleko tonkhe', netBalance: 'Ibhalansi lenethiwe',
    date: 'Lusuku', category: 'Uhlobo', description: 'Inchazelo', amount: 'Inani',
    paymentMethod: 'Indlela yekukhokha', referenceNumber: 'Inombolo yereferensi', notes: 'Emabala',
    addIncome: 'Engeta imali', addExpense: 'Engeta indleko', setBudget: 'Beka ibhajethili',
    monthlyLimit: 'Umkhawulo wenyanga', alertThreshold: 'Umngcele wecwayiso',
    noEntries: 'Akukho kurekhodwa', exportPdf: 'Khumula PDF', currency: 'Imali',
    saveBudget: 'Gcina ibhajethili', exceeded: 'Kudlulile', warning: 'Secwayiso', onTrack: 'Endleleni',
    spent: 'kusetjentisiwe', of: 'ya', getAiInsights: 'Tfola lucwaningo lwe-AI',
    analyzingFinances: 'Ihlaziya timali takho...',
    financialAdvisor: 'Umeluleki wetimali',
    advisorDesc: 'Umeluleki wetimali we-AI welipulazi lakho',
    askAdvisor: 'Buta umeluleki',
    advisorPlaceholder: 'Buta ngekuhlela imitselo, kutjalwa kwemali, kugeleta kwemali...',
    advisorThinking: 'Umeluleki wakho wetimali uyacabanga...',
    advisorWelcome: 'Umeluleki wakho wetimali welipulazi. Buta ngekugeleta kahle kwemali, emasu emitselo, kuhlela kutjalwa kwemali, noma kuphatfwa kwengoti.',
    sprayCalendar: 'Ikhalenda yekufafata',
    addSchedule: 'Engeta isikhathi', cropName: 'Ligama lesilimo', pesticideName: 'Ligama lemutsi',
    applicationDate: 'Lusuku lwekusebentisa', repeatInterval: 'Sikhatsi sekuphindza (emalanga)',
    scheduled: 'Kuhleliwe', completed: 'Kuphele', skipped: 'Kweciwe',
    markDone: 'Beka kuphele', skip: 'Yeca',
    smartIrrigation: 'Kunisela lokuhlakaniphile',
    cropSelection: 'Kukhetsa silimo', soilType: 'Luhlobo lwemhlaba',
    getAnalysis: 'Tfola lucwaningo', refreshAnalysis: 'Vuselela lucwaningo',
    waterNeeds: 'Tidzingo temanti', schedule: 'Isikhathi', tips: 'Imibiko',
    cropMonitoring: 'Kubuka tilimo',
    uploadCropImage: 'Layisha sitfombe sesilimo sekuhlolwa nge-AI',
    cropType: 'Luhlobo lwesilimo', plantingDate: 'Lusuku lwekutjala', growthStage: 'Sigaba sekukhula',
    selectCrop: 'Khetsa silimo', selectStage: 'Khetsa sigaba',
    analyzingCrop: 'Ihlaziya imphilo yesilimo...',
    climateRiskAnalysis: 'Lucwaningo lwengoti yelitulu',
    riskOverview: 'Kubuka kwengoti', adaptations: 'Kujwayela', forecast: 'Sibikezelo',
    research: 'Lucwaningo', liveConditions: 'Simo sanyalo', dataQuality: 'Bunjalo bedatha',
    knowledgeGraphExplorer: 'Sihloli segrafu yelwati',
    searchNodes: 'Tfuna tinodhi...', filterByType: 'Sefa ngeluhlobo',
    allTypes: 'Tonkhe tinhlobo', crops: 'Tilimo', treatments: 'Kulapha',
    diseases: 'Tifo', soilTypes: 'Tinhlobo temhlaba', seasons: 'Tikhatsi', regions: 'Tifundza',
    relationships: 'Budlelwane', relatedNodes: 'Tinodhi letihlobene',
    noRelationships: 'Kute budlelwane lobutfolakele',
    confidence: 'Kutsemba', strength: 'Emandla',
    africanMarketsTitle: 'Timakethe tase-Afrika',
    highDemandProducts: 'Imphahla letidingeka kakhulu nekutsintsana kwemakethe',
    pricesIn: 'Tintengo nge',
    products: 'Imiphahla', markets: 'Timakethe',
    allDemand: 'Sidzingo sonkhe', veryHigh: 'Siphakeme kakhulu', high: 'Siphakeme', moderate: 'Sisemkhatsini',
    refresh: 'Vuselela', season: 'Sikhatsi',
    marketContactsInfo: 'Timakethe letinkhulu tekulima e-Afrika. Tsintsana nato ngetintengo tekutsengisa.',
    farmActivities: 'Imisebenti yasepulazini', addActivity: 'Engeta umsebenti',
    activityType: 'Luhlobo lwemsebenti', activityDate: 'Lusuku lwemsebenti',
    loading: 'Kuyalayisha...', error: 'Siphosiso', success: 'Kuphumelela', cancel: 'Khansela',
    confirm: 'Cinisekisa', delete: 'Susa', edit: 'Hlela', close: 'Vala',
    noData: 'Akukho data', tryAgain: 'Zama futsi',
  },
};

interface LanguageContextType {
  lang: string;
  t: (key: string) => string;
  setLang: (lang: string) => void;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  t: (key) => key,
  setLang: () => {},
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem('imvelo_lang') || 'en');
  const { user } = useAuth();

  useEffect(() => {
    if (!user) return;
    supabase
      .from('profiles')
      .select('preferred_language')
      .eq('id', user.id)
      .single()
      .then(({ data }) => {
        if (data?.preferred_language) {
          setLangState(data.preferred_language);
          localStorage.setItem('imvelo_lang', data.preferred_language);
        }
      });
  }, [user]);

  const setLang = (newLang: string) => {
    setLangState(newLang);
    localStorage.setItem('imvelo_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
